### PR TITLE
Initial german translation

### PR DESCRIPTION
**Pull request by tweimer**
This is still work in progress, Many parts untranslated.

See #164

### CODE REVIEW

**Comment by tweimer** [comment]
@anxdpanic What is the difference between "Clear data cache" and "Delete data cache"? To me, both means the same thing.
A bit more explanation in the blue text would be helpful.

**Comment by anxdpanic** [comment]
@tweimer
`Clear data cache`: Removes/Clears the entries from the data cache database, leaving an empty database table
`Delete data cache`: Delete's the data cache database file, this would be used on a corrupt database usually

**Comment by tweimer** [comment]
@anxdpanic Thanks! Could you add that to the blue help text within the addon? I find that a bit hard to understand.

**Comment by anxdpanic** [comment]
Created an issue so I get to it soon 
https://github.com/anxdpanic/plugin.video.tubed/issues/180

**Comment by anxdpanic** [comment]
I updated the strings, in https://github.com/anxdpanic/plugin.video.tubed/pull/181 you might have to manually align these `msgid`s in your PR.

**Comment by tweimer** [comment]
@anxdpanic  Ready to merge!

**Review by anxdpanic — APPROVED** [review]
Huge thank you for this 👍

**Pull request merged**
